config/routes.rb
# routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root "contents#index"

  resources :contents, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    member do
      get :share
    end
    collection do
      post :preview_summary
    end
  end

  resources :comments

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      delete :remove_avatar
    end
    collection do
      get :check_email
      get   :signup_sent
      get   :edit_password
      patch :update_password
      get  :finish_sign_up
    end
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: :logout
  get "/signup_sent", to: "users#signup_sent", as: :signup_sent
  get  "/users/finish_sign_up", to: "users#finish_sign_up"
  get '/users/check_email', to: 'users#check_email'

  match "*path",
    to: "application#render_404",
    via: :all,
    constraints: ->(req){ !req.path.start_with?("/rails") }
end

app/views/layouts/_search.html.erb
<%= form_with url: contents_path, local: true, method: :get do |f| %>
  <div class="input-group rounded-pill overflow-hidden" style="max-width:500px;">
    <span class="input-group-text bg-white border-0" style="opacity:0.8;">
      <i class="fa-solid fa-magnifying-glass text-muted"></i>
    </span>
    <%= f.text_field :word, class: "form-control border-0", placeholder: "Search", autocomplete: "off", style: "opacity:0.8;" %>
  </div>
<% end %>

app/views/layouts/application.html copy.erb
<%# /app/views/layouts/application.html.erb %>
<!DOCTYPE html>
<html lang="ja" data-bs-theme="auto" class="d-flex justify-content-center">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="…" crossorigin="anonymous">
  <!-- FontAwesome -->
  <script src="https://kit.fontawesome.com/4535843fc0.js" crossorigin="anonymous"></script>
  <!-- FirebaseUI CSS -->
  <link href="https://www.gstatic.com/firebasejs/ui/6.1.0/firebase-ui-auth.css" rel="stylesheet">
  <!-- Firebase compat scripts (window.firebase を定義) -->
  <script src="https://www.gstatic.com/firebasejs/11.1.0/firebase-app-compat.js"></script>
  <script src="https://www.gstatic.com/firebasejs/11.1.0/firebase-auth-compat.js"></script>
  <!-- FirebaseUI -->
  <script src="https://www.gstatic.com/firebasejs/ui/6.1.0/firebase-ui-auth.js"></script>

  <%= javascript_importmap_tags %>
  
  <script type="module" src="<%= asset_path 'auth_signup_password.js' %>"></script>
  <link rel="icon" href="/favicon.ico" sizes="16x16" type="image/png">
  <title>Omatomedia - おまとめ情報サイト</title>
</head>

<body class="d-flex flex-column min-vh-100">
  <% if current_page?(login_path) || current_page?(new_user_path) %>
    <%= yield %>
  <% else %>
    <!-- ナビバー -->
    <nav class="navbar fixed-top" style="background-color: #FAD02C;">
      <div class="container-fluid d-flex justify-content-between align-items-center" style="height:50px;">
        <!-- ① 左側：ロゴ -->
        <%= link_to image_tag("omatome-logo2.png", size: "180x50", alt: "Omatomediaロゴ"), root_path %>
        <!-- ② 中央：検索フォームを中央寄せ -->
        <div class="flex-grow-1 d-flex justify-content-center">
          <%= render "layouts/search" %>
        </div>
        <!-- ③ 右側：ログイン中のみ、または未ログイン時のリンク -->
        <div class="d-flex align-items-center ms-auto">
        <%= link_to "upload", new_content_path, class: "btn btn-light btn-sm mx-2", style:"opacity:80%;" %>
          <% if logged_in? %>
            <!-- ユーザードロップダウン -->
            <div class="dropdown">
              <a id="dropdownButton" class="d-flex align-items-center text-decoration-none dropdown-toggle text-dark"
                href="#" id="userDropdown" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.avatar.attached? %>
                  <%= image_tag current_user.avatar.variant(resize_to_fill: [32,32]),
                    class: "rounded-circle", alt: "#{current_user.name}のアバター" %>
                <% else %>
                  <%= image_tag "noimage.png", size: "32x32",
                    class: "rounded-circle", alt: "デフォルトアバター" %>
                <% end %>
                <span class="px-2"><strong><%= current_user.name %></strong></span>
              </a>

              <ul id="dropdownMenu" class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                <li><%= link_to "My page", user_path(current_user), class: "dropdown-item text-dark" %></li>
                <li><%= link_to "Logout", logout_path, method: :delete, id: "sign-out", class: "dropdown-item text-dark", data: { turbo: false }  %></li>
              </ul>
            </div>
          <% else %>
            <!-- 未ログイン時はログインリンクだけ -->
            <%= link_to "Login", login_path, class: "btn btn-sm btn-outline-dark w-100" %>
          <% end %>
        </div>
      </div>
    </nav>

      <div class="container my-4">
        <!-- カテゴリ絞り込みナビ -->
        <ul class="nav nav-pills mb-4 justify-content-center">
          <li class="nav-item">
            <%= link_to "All", contents_path, 
                  class: "nav-link #{'active' if params[:category_id].blank?}" %>
          </li>
          <% @categories.each do |cat| %>
            <li class="nav-item">
              <%= link_to cat.name, contents_path(category_id: cat.id),
                    class: "nav-link #{'active' if params[:category_id].to_i == cat.id}" %>
            </li>
          <% end %>
        </ul>

        <!-- コンテンツ一覧 -->
        <div class="row">
          <%= yield %>
        </div>
      </div>
  <% end %>

  <!-- フッター-->
  <footer class="footer mt-auto py-2 bg-light">
    <div class="container text-center">
      <small class="text-muted">All rights reserved by MeRock</small>
    </div>
  </footer>

  <%# <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script> %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" data-bs-theme="auto" >

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/4535843fc0.js" crossorigin="anonymous"></script>
  <link rel="icon" type="image/png" href="/favicon_miyacco.png" sizes="16x16">
  <title>Miyacco - casual but useful news around the world</title>
</head>

<body class="wrapper">

    <% if current_page?(login_path)||current_page?(new_user_path) %>
      <div class="d-flex align-items-center justify-content-center text-center">
        <%= yield %>
      </div>
    <% else %>
    <%# nav bar %>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Obrest</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample04">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <%# <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li> %>
          </ul>
          <form class="me-2" role="search">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
          </form>
          <div>
              <% if logged_in? %>
                <div class="dropdown">
                  <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="me-2">
                      <% if current_user.avatar.attached? %>
                        <%= image_tag(current_user.avatar, class: "rounded-circle") %>
                      <% else %>
                        <%= image_tag("noimage.png", size: "32x32", class: "rounded-circle") %>
                      <% end %>
                    </div>
                    <strong><%= current_user.name %></strong>
                  </a>
                  <ul class="dropdown-menu text-small shadow">
                    <li><%= link_to "My page", user_path(current_user), class: "dropdown-item" %></li>
                    <li><%= link_to "Sign Out", logout_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
                  </ul>
                </div>
              <% elsif current_page?(login_path) %>
                <%= link_to "Create new account", new_user_path, class: "nav-link" %>
              <% else %>
                <%= link_to "Login", login_path, class: "nav-link" %>
              <% end %>
          </div>
        </div>
      </div>
    </nav>

  <div class="row">

    <%# saide bar %>
    <div class="col-3 card mt-3 p-2 ">
      <div class="d-flex flex-column flex-shrink-0 p-3">
          <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
            <% if current_page?('/') %>
              <a href="/" class="nav-link active link-body-emphasis">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
                </svg>
                Home
              </a>
            <% else %>
              <a href="/" class="nav-link link-body-emphasis">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
                </svg>
                Home
              </a>
            <% end %>
            </li>
            <li class="nav-item">
              <% if current_page?('/contents/1') %>
                <a href="/contents/1" class="nav-link active link-body-emphasis">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-newspaper" viewBox="0 0 16 16">
                    <path d="M0 2.5A1.5 1.5 0 0 1 1.5 1h11A1.5 1.5 0 0 1 14 2.5v10.528c0 .3-.05.654-.238.972h.738a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 1 1 0v9a1.5 1.5 0 0 1-1.5 1.5H1.497A1.497 1.497 0 0 1 0 13.5v-11zM12 14c.37 0 .654-.211.853-.441.092-.106.147-.279.147-.531V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v11c0 .278.223.5.497.5H12z"/>
                    <path d="M2 3h10v2H2V3zm0 3h4v3H2V6zm0 4h4v1H2v-1zm0 2h4v1H2v-1zm5-6h2v1H7V6zm3 0h2v1h-2V6zM7 8h2v1H7V8zm3 0h2v1h-2V8zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1z"/>
                  </svg>
                    Topics
                </a>
              <% else %>
                <a href="/contents/1" class="nav-link link-body-emphasis">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-newspaper" viewBox="0 0 16 16">
                    <path d="M0 2.5A1.5 1.5 0 0 1 1.5 1h11A1.5 1.5 0 0 1 14 2.5v10.528c0 .3-.05.654-.238.972h.738a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 1 1 0v9a1.5 1.5 0 0 1-1.5 1.5H1.497A1.497 1.497 0 0 1 0 13.5v-11zM12 14c.37 0 .654-.211.853-.441.092-.106.147-.279.147-.531V2.5a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0-.5.5v11c0 .278.223.5.497.5H12z"/>
                    <path d="M2 3h10v2H2V3zm0 3h4v3H2V6zm0 4h4v1H2v-1zm0 2h4v1H2v-1zm5-6h2v1H7V6zm3 0h2v1h-2V6zM7 8h2v1H7V8zm3 0h2v1h-2V8zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1zm-3 2h2v1H7v-1zm3 0h2v1h-2v-1z"/>
                  </svg>
                    Topics
                </a>
              <% end %>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link link-body-emphasis">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"/></svg>
                Latest
              </a>
            </li>
            <li>
              <a href="#" class="nav-link link-body-emphasis">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"/></svg>
                Events
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link link-body-emphasis">
                <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"/></svg>
                Travel
              </a>
            </li>
          </ul>
      </div>
    </div>
    <div class="col-9">
      <%# deivseのフラッシュメッセージを表示 %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>


  </div>

  <% end %>
</body>

<footer class="footer">
  <div class="container">
    <p class="text-muted text-center mt-2">all rights reserved by MeRock</p>
  </div>
</footer>

</html>